# Generated by Django 2.1.7 on 2019-03-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
