# Generated by Django 2.1.7 on 2019-03-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locallibrary', '0002_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
